INSERT INTO "settings" ( "key", "value") VALUES
('auth.ban_threshold',	'20'	),
('auth.ban_duration',	'24h'	),
('auth.lockout_duration',	'600s'	),
('auth.token_expiry',	'3600'	),
('auth.max_login_attempts',	'5'	),
('app.name',	'corebase'	),
('notifications.enabled',	'true'	),
('rate_limit',	'10'	),
('server.read_timeout',	'15'	),
('server.write_timeout',	'15'	),
('server.idle_timeout',	'60'	),
('cors.enabled',	'true'	),
('cors.allow_methods',	'["GET", "POST", "PUT", "DELETE"]'	),
('cors.allow_headers',	'["Content-Type", "Authorization"]'	),
('cors.allow_credentials',	'true'	),
('uploads.max_file_size',	'5242880'	),
('uploads.allowed_types',	'["jpg", "png", "pdf", "docx"]'	),
('uploads.storage_path',	'/var/www/uploads'	),
('session.timeout',	'1800'	);
-- 2025-07-11 12:45:08 UTC