apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: YXV0aGRi # authdb
  POSTGRES_USER: YXV0aHVzZXI= # authuser
  POSTGRES_PASSWORD: c2VjcmV0MTIz # secret123
